- name: register current docker-compose version
  ansible.builtin.shell: docker-compose --version | awk '{print $NF}'
  register: docker_compose_current_version

- name: register latest version
  ansible.builtin.shell: curl --silent "https://api.github.com/repos/docker/compose/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
  args:
    warn: false
  register: docker_compose_version

- name: install docker-compose
  ansible.builtin.get_url:
    url: https://github.com/docker/compose/releases/download/{{ docker_compose_version.stdout }}/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '755'
  when:
    docker_compose_current_version.stdout != docker_compose_version.stdout
